### ISSUE TITLE
Integration with logging

### ISSUE THREAD

**Issue by eAUE** [FRC2706/2018-2706-Robot-Code#7]
Should have the option to view logs from the robot.

**Comment by ounsworth** [comment]
Yeah, awesome to be able to see robot logs from the driver station.

Maybe have a checkbox or something to disable streaming of log data from the robot? I worry that we'll leave log data streaming during a match, which might cause the webcam to drop frames because of the very small amount of Robot <-> DS bandwidth that FIRST lets us have.

**Comment by eAUE** [comment]
We were thinking of making it an on-demand function, so it will only download when the user presses the button

**Comment by ounsworth** [comment]
Perfect. Once this is working, we should test with Wireshark on the DS computer to be sure it's not a "download anyway but don't display" kind of thing. (I can help with the Wireshark part if you need)
